### ISSUE TITLE
Announce duplicacy autobackup on forum 

### ISSUE THREAD

**Issue by papatistos** [christophetd/duplicacy-autobackup#11]
Looks like you've done a magnificent job here. It would be great if you could post about this on the new duplicacy forum at forum.duplicacy.com.

**Comment by christophetd** [comment]
Thanks! Will do

**Comment by christophetd** [comment]
Looks like you took care of it! https://forum.duplicacy.com/t/duplicacy-autobackup-docker-image/1017 Cheers
