### ISSUE TITLE
How to use multiple destinations?

### ISSUE THREAD

**Issue by skhaz** [christophetd/duplicacy-autobackup#13]
Is that possible[1]?

1 - https://github.com/gilbertchen/duplicacy/wiki/Back-up-to-multiple-storages

**Comment by christophetd** [comment]
Unfortunately that's not supported right now. Other people who would be interested by this feature, please vote with a thumbs up. :-)

**Comment by christophetd** [comment]
Hey @skhaz,

Since 3 other people have voted, I'm willing to look into this feature. What do you think it should you like? In the current state, the configuration of the destination is made via environment variables. I don't think this is feasible for multiple destination, and I'd like to find a way to keep it simple.

**Comment by skhaz** [comment]
Hi @christophetd 

I'm not using duplicacy anymore and neither docker for containerization, my current setup is the borgmatic instead of duplicacy running inside a FreeBSD's jail.

Anyways, as soon I have some spare time I'll try figure out some way to develop this feature.

**Comment by christophetd** [comment]
Thanks for the feedback! Out of personal curiosity, what are some features in Borgmatic that you feel outperform duplicacy?

**Comment by alek-zstd** [comment]
@christophetd I think having multiple backup locations would be great! Currently having to create two separate containers. I have it setup to run a local backup and google drive. Off the top of my head would having to env variables be feasible? Or maybe passing comma separated destination strings?

**Comment by christophetd** [comment]
Probably the best way indeed. How would something like this look to you?

```
$ docker run -d --name duplicacy-autobackup \
    -v /var/lib/mysql:/data \
    -e BACKUP_NAME='prod-db-backups' \
    -e BACKUP_LOCATION='s3://eu-west-1@amazon.com/xtof-db-backups,s3://us-west-1@amazon.com/xtof-db-backups2,b2://db-backups' \
    -e BACKUP_SCHEDULE='0 2 * * *' \
    -e BACKUP_ENCRYPTION_KEY='correct horse battery staple' \
    -e AWS_ACCESS_KEY_ID='AKIA...' \
    -e AWS_SECRET_KEY='...' \
    -e BACKBLAZE_xxx='xxx' \
    christophetd/duplicacy-autobackup
```

**Comment by alek-zstd** [comment]
Yeah that's what I was thinking!

**Comment by cerealconyogurt** [comment]
Hi, I was planning also to use two docker instance to manage multiple backup, but maybe the best and efficiency approach should be add the copy command to the script.
