### ISSUE TITLE
Prune after backup option?

### ISSUE THREAD

**Issue by rsuplido** [christophetd/duplicacy-autobackup#14]
Thanks for this! Can I ask for a prune option that probably runs after the backup? Something that does:

`duplicacy prune -keep 0:30     # Keep no snapshots older than 30 days`

More info: https://forum.duplicacy.com/t/prune-command-details/1005

Thanks.

**Comment by rsuplido** [comment]
nvm, I just looked at the code and you can bind to a /scripts folder where it runs a pre-backup.sh and/or post-backup.sh if exists. I just created a post-backup.sh with:

`duplicacy prune -keep 0:30`

and it runs at the end:

> ...
> Total running time: 00:00:09
> Running post-backup script
> Storage set to dropbox://_snapshotId_
> Keep no snapshots older than 30 days
> No snapshot to delete
> Post-backup script exited with status 0

Thanks for adding that option.

**Comment by christophetd** [comment]
I was unsure whether anyone would ever use this option, so I'm glad you actually need it. :-)

**Comment by christophetd** [comment]
FYI, out of the box prune support has just been added in #17
