### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by gingerlime** [christophetd/duplicacy-autobackup#18]
Perhaps this project doesn't need lots of updates, but the latest commit was almost a year ago now. There's a PR to bump duplicacy version to 2.1.2 that's open for a couple of weeks without any activity... Just wondering since I was thinking of using it

**Comment by christophetd** [comment]
Hi, 

To be transparent with you I have not touched the project in a year as you say, but I'm actively using it for personal backups on my side. I haven't merged the 2 PRs yet because I did not have the time to test them properly.

Cheers

**Comment by gingerlime** [comment]
Thank you @christophetd. It's good to know :)
