### ISSUE TITLE
Backblaze B2 - B2_ID with Application Key ID instead of Master Application Key ID doesn't work

### ISSUE THREAD

**Issue by stenioaraujo** [christophetd/duplicacy-autobackup#19]
Duplicacy version 2.1.0 only allows the B2_ID to be set to the Master Application Key ID. This issue was fixed on version 2.1.2 of the Duplicacy CLI.

Application Keys are used to limit permission access to the Buckets. With the right permission, one can enable write only to a bucket by not allowing delete capabilities.

**Comment by christophetd** [comment]
Thanks for the issue and the PR. As I mention in #20, it sounds like a good idea to be able to choose at build time which version of duplicacy to use. Does that seem like an acceptable solution to you?

**Comment by stenioaraujo** [comment]
Hi, thank you for looking into it. I think adding an argument at build time solves the issue. It makes it easy for tagging the image based on the duplicacy version as well.

**Comment by christophetd** [comment]
Great, I'll look into implementing that. PR welcome if you're in a hurry :)

**Comment by stenioaraujo** [comment]
I will be glad to send a PR myself, you have done a great job already, that is the minimum I can do :P. Thank you.
