### ISSUE TITLE
Feature to exclude files/ folders

### ISSUE THREAD

**Issue by Stiefmeister** [christophetd/duplicacy-autobackup#30]
Is it possible to exclude specific files/ folders mounted in /data ?

As I have limited online storage I can only select a limited set of files/ folders for remote backup. Would simplify things a lot if you could just exclude those. 

Thanks a lot!

**Comment by mark-monteiro** [comment]
This is a supported feature in duplicacy: https://github.com/gilbertchen/duplicacy/wiki/Include-Exclude-Patterns

In summary, you need to have a file named `filters` in the `.duplicacy` directory that contains your filters. The `.duplicacy` directory is created when the initializing the repository.

**Comment by christophetd** [comment]
Thanks Mark for the response!
