### ISSUE TITLE
A couple notes/possible improvements

### ISSUE THREAD

**Issue by alexbaucom17** [christophetd/duplicacy-autobackup#5]
Here are a couple suggestions for possible improvements or notes to put in the README based on my experience of getting this up and running.

- The cron job timing will use the UTC timezone since docker doesn't sync with the system clock. There are some workarounds that can take in an environment variable [like this](https://forums.docker.com/t/synchronize-timezone-from-host-to-container/39116) but the easiest workaround for me was just to set the timing based on UTC. I am PST and I want to run at midnight, so I just used `0 7 * * *`. May be worth putting a note about this in the README if you aren't interested in adding the environment variable option.
- I was getting very poor backup speeds until I removed `-threads 4` so that duplicacy would run single threaded. With 4 threads I was getting about 100kB/s at steady state and with only a single thread I'm getting closer to 1MB/s. [This post](https://duplicacy.com/issue?id=5670666258874368) has some good info about this. Again, if you don't want to modify that in the Dockerfile since 4 threads works well for your needs, it may be worth at least adding a note to the README.

**Comment by christophetd** [comment]
Thanks a bunch for the suggestions! I'll definitely take that into account in the next days.
